"""Export helpers — Markdown and PDF generation for analysis results."""

from datetime import datetime
from fpdf import FPDF

# ── Unicode → ASCII sanitizer ─────────────────────────────────────────────────

_UNICODE_MAP = str.maketrans({
    # Dashes
    "\u2010": "-",  # hyphen
    "\u2011": "-",  # non-breaking hyphen
    "\u2012": "-",  # figure dash
    "\u2013": "-",  # en dash
    "\u2014": "--", # em dash
    "\u2015": "--", # horizontal bar
    # Quotes
    "\u2018": "'",  "\u2019": "'",   # curly single quotes
    "\u201c": '"',  "\u201d": '"',   # curly double quotes
    "\u201a": ",",  "\u201e": '"',
    "\u2032": "'",  "\u2033": '"',   # prime / double prime
    # Bullets & misc
    "\u2022": "*",  "\u2023": "*",   # bullet
    "\u2026": "...",                  # ellipsis
    "\u00b7": ".",                    # middle dot
    "\u2019": "'",                    # right single quotation
    "\u00a0": " ",                    # non-breaking space
    "\u200b": "",                     # zero-width space
    "\u2060": "",                     # word joiner
})


def _s(text: str) -> str:
    """Sanitize text for Helvetica: replace unsupported Unicode with ASCII."""
    text = text.translate(_UNICODE_MAP)
    # Drop any remaining non-Latin-1 characters
    return text.encode("latin-1", errors="ignore").decode("latin-1")


# ── Markdown ──────────────────────────────────────────────────────────────────

def to_markdown(data: dict) -> str:
    """Convert an analysis result dict to a well-structured Markdown string."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = []

    lines.append(f"# {data.get('title', 'Website Analysis')}")
    lines.append(f"\n> Exported on {now}")
    lines.append(f"\n**URL:** {data.get('url', '')}\n")

    if data.get("description"):
        lines.append(f"**Description:** {data['description']}\n")

    if data.get("summary"):
        lines.append("---\n\n## Summary\n")
        lines.append(data["summary"])

    if data.get("key_points"):
        lines.append("\n\n---\n\n## Key Points\n")
        for point in data["key_points"]:
            lines.append(f"- {point}")

    if data.get("topics"):
        lines.append("\n\n---\n\n## Topics\n")
        lines.append(", ".join(data["topics"]))

    if data.get("keywords"):
        lines.append("\n\n---\n\n## Keywords\n")
        lines.append(", ".join(data["keywords"]))

    if data.get("headings"):
        lines.append("\n\n---\n\n## Page Structure\n")
        for h in data["headings"]:
            lines.append(f"- {h}")

    links = data.get("links", [])
    if links:
        lines.append("\n\n---\n\n## Links\n")
        lines.append(f"Total: {len(links)}\n")
        lines.append("| URL | Text | Type |")
        lines.append("|---|---|---|")
        for lnk in links:
            href = lnk.get("href", "")
            text = lnk.get("text", "").replace("|", "\\|")
            ltype = lnk.get("type", "")
            lines.append(f"| {href} | {text} | {ltype} |")

    lines.append(f"\n\n---\n\n*Generated by Website Descriptor · {now}*")
    return "\n".join(lines)


# ── PDF ───────────────────────────────────────────────────────────────────────

# A4: width=210mm, margins 15mm each side → usable width = 180mm
_PAGE_W = 180  # mm, used for explicit cell widths


def _wrap(text: str, max_chars: int = 120) -> str:
    """Break any single token longer than max_chars with a zero-width space
    so fpdf2 can wrap long URLs and similar strings."""
    words = text.split(" ")
    out = []
    for w in words:
        if len(w) > max_chars:
            # Insert a space every max_chars characters
            w = " ".join(w[i:i+max_chars] for i in range(0, len(w), max_chars))
        out.append(w)
    return " ".join(out)


def _safe(text: str) -> str:
    """Sanitize + wrap for PDF output."""
    return _wrap(_s(text))


class _PDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def __init__(self, title: str):
        super().__init__(format="A4")
        self._doc_title = _s(title)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 80, 80)
        self.cell(_PAGE_W, 8, self._doc_title[:90], align="L")
        self.set_text_color(0, 0, 0)
        self.ln(10)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.cell(_PAGE_W, 8, f"Website Descriptor  {now}  Page {self.page_no()}", align="C")


def _add_section(pdf: _PDF, heading: str, body_lines: list[str], bullet: bool = False) -> None:
    """Add a titled section with body text to the PDF."""
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(_PAGE_W, 8, _s(heading), ln=True, fill=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", size=10)
    for line in body_lines:
        prefix = "*  " if bullet else ""
        pdf.multi_cell(_PAGE_W, 6, _safe(f"{prefix}{line}"), align="L")
    pdf.ln(4)


def to_pdf(data: dict) -> bytes:
    """Convert an analysis result dict to PDF bytes using fpdf2."""
    title = data.get("title", "Website Analysis")
    pdf = _PDF(title=title)
    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Title block ───────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.multi_cell(_PAGE_W, 10, _safe(title), align="L")
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(_PAGE_W, 6, _safe(data.get("url", "")), align="L")
    if data.get("description"):
        pdf.ln(2)
        pdf.multi_cell(_PAGE_W, 6, _safe(data["description"]))
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── Summary ───────────────────────────────────────────────────────────────
    if data.get("summary"):
        _add_section(pdf, "Summary", [data["summary"]])

    # ── Key Points ────────────────────────────────────────────────────────────
    if data.get("key_points"):
        _add_section(pdf, "Key Points", data["key_points"], bullet=True)

    # ── Topics ────────────────────────────────────────────────────────────────
    if data.get("topics"):
        _add_section(pdf, "Topics", [", ".join(data["topics"])])

    # ── Keywords ─────────────────────────────────────────────────────────────
    if data.get("keywords"):
        _add_section(pdf, "Keywords", [", ".join(data["keywords"])])

    # ── Page structure ────────────────────────────────────────────────────────
    if data.get("headings"):
        _add_section(pdf, "Page Structure", data["headings"], bullet=True)

    # ── Links summary ─────────────────────────────────────────────────────────
    links = data.get("links", [])
    if links:
        n_int = sum(1 for lnk in links if lnk.get("type") == "internal")
        n_ext = len(links) - n_int
        _add_section(pdf, "Links", [
            f"Total: {len(links)}  |  Internal: {n_int}  |  External: {n_ext}",
        ])

    return bytes(pdf.output())
